public class MYSampleApexClass{				//class definition and body
	public static Integer myValue =0;		// class Member variable
	public static Integer myString =' ';	// class Member variable
	public static Integer myString5 =' ';	//class Member variable
	public static Integer myString7 =' ';	//class Member variable
	public static Integer variable1 =' ';	//class Member variable
	public static Integer variable2 =' ';	//class Member variable
	public static Integer myString3 =' ';	//class Member variable
	public static Integer myString2 =' ';	//class Member variable
}



public static Integer getCalculatedvalue () {
	//Method definition and body
	//do some calculation
	
	myValue=myValue+10;
	tetsing going on;
	return myValue;
}