public class DemoSampleClass {
    public static void firstMethod()
    {
        System.debug('hello');
        System.debug('mukul');
        System.debug('hello world');
        System.debug('hi i am mukul');
        System.debug('hi i am mukul');
        System.debug('hi i am mukul');
        System.debug('hi i am mukul');
        
           System.debug('testing ');
        
        

    }

}